media:
  input: public
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view:
      fields: [ title, draft, date ]
    fields:
      - name: contact
        label: Contact information
        type: object
        fields:
          - name: first_name
            name: First name
            type: string
          - name: last_name
            name: Last name
            type: string
          - name: email
            name: Email address
            type: string
          - name: phone
            name: Phone number
            type: string
  - name: about
    label: About page
    type: file
    path: src/pages/about.md
    fields:
      - { name: layout, type: string, hidden: true, default: layouts/base.njk }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
